map:
  name: "race-2"
  dir: "Maps/Offroad"
  size: [512, 512]
  res: &map_res 0.1
  test_cases:
    case1:
      start: [5.6, 8.9, 1.5844149127199794, 4.935323678240241, 0]
      goal: [21.1, 46.1, 0.608009209539623, 4.516091247319389, 0]
    case2:
      start: [11.9, 16.8, 1.3574384016819936, 3.317266656251059, 0]
      goal: [46.6, 25.0, 0.19076360687480998, 3.2507584385704855, 0]
    case3:
      start: [39.6, 48.2, -1.2370255478869705, 3.0573288502453986, 0]
      goal: [42.7, 14.0, -2.0729059377472634, 3.084950697597427, 0]
experiment_info_default:
  resolution: 4.0 # starting resolution used for discretization.
  epsilon: [2, 2, 0.2, 5.0] # ate, cte, heading, vel for goal region.
  tolerance: 0.5 # Your perception (map) resolution should be at least this.
  max_level: 5 # maximum level to which you expect the system to go; we use this to cache the hash values.
  division_factor: 2  # factor by which the resolution increases every level.
  max_expansions: 100000 # maximum number of expansions allowed.
  hysteresis: 1000 # hysteresis threshold for for IGHA*-H
  node_info:
    node_type: "kinodynamic"
    length: 2.6
    width: 1.6 # actual car width is 1.5
    map_res: *map_res
    dt: 0.05
    timesteps: 10
    step_size: 1.0
    steering_list: [-25.0, -10.0, 0.0, 10.0, 25.0] # in degrees.
    throttle_list: [-5.0, 0, 5.0]
    del_theta: 90.0 # in degrees
    del_vel: 2.5
    RI: 0.8
    max_vert_acc: 3.0
    min_vel: -10.0
    max_vel:  10.0
    max_theta: 30.0 # in degrees
    gear_switch_time: 1.0