map: 
  name: "17_512.png"
  dir: "Maps/generated_maps/multi_bottleneck"
  size: [512, 512]
  res: &map_res 1
  test_cases:
    case1:
      start: [41, 141]
      goal: [475, 463]
experiment_info_default:
  resolution: 20.0
  epsilon: [20, 20] # ate, cte, heading, vel
  tolerance: 0.01
  max_level: 5
  division_factor: 2  # Example division factor
  max_expansions: 100000
  hysteresis: 1000
  node_info:
    node_type: "simple"
    step_size: 25.0
    n_succ: 8
    timesteps: 20
    map_res: *map_res